name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # main 브랜치에 코드가 push될 때만 실행됩니다.
    paths:
      - "**/*" # 모든 변경사항에 대해 트리거 (원하는 경로로 수정 가능)

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🐳 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🔑 Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 🚀 Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .  # .github 폴더가 현재 robot_mlops/ 최상단과 일치한다고 가정
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/robot-mlops-eye:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/robot-mlops-eye:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/robot-mlops-eye:buildcache,mode=max

  deploy:
    needs: build-and-push-image
    runs-on: self-hosted
    steps:
      - name: 🔑 Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 📥 Pull latest image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/robot-mlops-eye:latest

      - name: 🛑 Stop and remove existing container
        run: |
          $containerName = "robot-mlops-eye"
          if (docker ps -a --filter "name=$containerName" --format "{{.Names}}" | Select-String -Pattern "^$containerName$") {
            Write-Host "Stopping and removing existing container: $containerName"
            docker stop $containerName
            docker rm $containerName
          }
        shell: powershell

      - name: 🚀 Run new container
        run: docker run -d --name robot-mlops-eye -p 8000:8000 ${{ secrets.DOCKERHUB_USERNAME }}/robot-mlops-eye:latest
